rm(list = ls())
data_1 <- read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
data_2 <- data_1[data_1$Date %in% c("1/2/2007","2/2/2007") ,]
time_axis <- strptime(paste(data_2$Date, data_2$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("plot3.png", width=480, height=480)
plot(time_axis, as.numeric(data_2$Sub_metering_1), type="l", ylab="Energy Submetering", xlab="")
lines(time_axis, as.numeric(data_2$Sub_metering_2), type="l", col="red")
lines(time_axis, as.numeric(data_2$Sub_metering_3), type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()